version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: lfx-organizations-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build: ./service
    container_name: lfx-organizations-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
      - NODE_ENV=production
    volumes:
      - ./service:/app
      - /app/node_modules
    command: >
      sh -c "
        node -v &&
        npm run db:gen &&
        npm run db:migrate &&
        npm run seed &&
        npm start
      "
    ports:
      - "3000:3000"
    

volumes:
  pgdata:
